name: Greet User

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
      color:
        description: 'Enter your favorite color'
        required: true

jobs:
  greet_user:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello ${{ github.event.inputs.name }}! Your favorite color is ${{ github.event.inputs.color }}" 
